import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

import {NextIntlClientProvider} from 'next-intl';
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";

const robotoSans = Roboto({
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nextjs template",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      className={`${robotoSans.className} ${robotoMono.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col preload-theme-remover dark:selection:bg-[#7D3127]! selection:bg-[#51ABB5]!">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <NextIntlClientProvider messages={messages}>
            <TooltipProvider>
              {/*My Header forked from https://github.com/mehrdadrafiee/animated-header*/}
              <Header/>
              <main className="mx-6 my-3 sm:mx-18 sm:my-7 md:mx-36 md:my-14 flex flex-1">
                {children}
              </main>
              <Footer/>
            </TooltipProvider>
            <Toaster />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
